version: '3.8'
services:
  dataloader:
    container_name: dataloader-edmachina
    restart: on-failure:3
    build: ./data_load
    depends_on:
      - postgres
      - app
  app:
    container_name: backend-edmachina
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    container_name: postgres-edmachina
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=edmachina
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - backendDB:/data/db

volumes:
  backendDB: